vich_uploader:
    db_driver: orm

    mappings:
        championshipLogos:
            uri_prefix: /images/championshipLogos
            upload_destination: '%kernel.project_dir%/public/images/championshipLogos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        clubLogos:
            uri_prefix: /images/clubLogos
            upload_destination: '%kernel.project_dir%/public/images/clubLogos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer