<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20200815131302 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP INDEX IDX_EBADDE6A4EC001D1');
        $this->addSql('CREATE TEMPORARY TABLE __temp__championship AS SELECT id, season_id, name, description, logo, number_competition_max4_calculus, is_internal, updated_at FROM championship');
        $this->addSql('DROP TABLE championship');
        $this->addSql('CREATE TABLE championship (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, season_id INTEGER NOT NULL, name VARCHAR(255) NOT NULL COLLATE BINARY, description CLOB DEFAULT NULL COLLATE BINARY, logo VARCHAR(255) NOT NULL COLLATE BINARY, number_competition_max4_calculus INTEGER NOT NULL, is_internal BOOLEAN NOT NULL, updated_at DATETIME NOT NULL, CONSTRAINT FK_EBADDE6A4EC001D1 FOREIGN KEY (season_id) REFERENCES season (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO championship (id, season_id, name, description, logo, number_competition_max4_calculus, is_internal, updated_at) SELECT id, season_id, name, description, logo, number_competition_max4_calculus, is_internal, updated_at FROM __temp__championship');
        $this->addSql('DROP TABLE __temp__championship');
        $this->addSql('CREATE INDEX IDX_EBADDE6A4EC001D1 ON championship (season_id)');
        $this->addSql('DROP INDEX IDX_D93D873294DDBCE9');
        $this->addSql('DROP INDEX IDX_D93D873261190A32');
        $this->addSql('CREATE TEMPORARY TABLE __temp__championship_rank_club AS SELECT id, championship_id, club_id, rank, score FROM championship_rank_club');
        $this->addSql('DROP TABLE championship_rank_club');
        $this->addSql('CREATE TABLE championship_rank_club (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, championship_id INTEGER NOT NULL, club_id INTEGER NOT NULL, rank INTEGER NOT NULL, score INTEGER NOT NULL, CONSTRAINT FK_D93D873294DDBCE9 FOREIGN KEY (championship_id) REFERENCES championship (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_D93D873261190A32 FOREIGN KEY (club_id) REFERENCES club (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO championship_rank_club (id, championship_id, club_id, rank, score) SELECT id, championship_id, club_id, rank, score FROM __temp__championship_rank_club');
        $this->addSql('DROP TABLE __temp__championship_rank_club');
        $this->addSql('CREATE INDEX IDX_D93D873294DDBCE9 ON championship_rank_club (championship_id)');
        $this->addSql('CREATE INDEX IDX_D93D873261190A32 ON championship_rank_club (club_id)');
        $this->addSql('DROP INDEX IDX_33BEFAAE94DDBCE9');
        $this->addSql('DROP INDEX IDX_33BEFAAE99E6F5DF');
        $this->addSql('CREATE TEMPORARY TABLE __temp__championship_rank_player AS SELECT id, championship_id, player_id, rank, score FROM championship_rank_player');
        $this->addSql('DROP TABLE championship_rank_player');
        $this->addSql('CREATE TABLE championship_rank_player (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, championship_id INTEGER NOT NULL, player_id INTEGER NOT NULL, rank INTEGER NOT NULL, score INTEGER NOT NULL, CONSTRAINT FK_33BEFAAE94DDBCE9 FOREIGN KEY (championship_id) REFERENCES championship (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_33BEFAAE99E6F5DF FOREIGN KEY (player_id) REFERENCES player (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO championship_rank_player (id, championship_id, player_id, rank, score) SELECT id, championship_id, player_id, rank, score FROM __temp__championship_rank_player');
        $this->addSql('DROP TABLE __temp__championship_rank_player');
        $this->addSql('CREATE INDEX IDX_33BEFAAE94DDBCE9 ON championship_rank_player (championship_id)');
        $this->addSql('CREATE INDEX IDX_33BEFAAE99E6F5DF ON championship_rank_player (player_id)');
        $this->addSql('ALTER TABLE club ADD COLUMN updated_at DATETIME');
        $this->addSql('DROP INDEX IDX_B50A2CB194DDBCE9');
        $this->addSql('CREATE TEMPORARY TABLE __temp__competition AS SELECT id, championship_id, name, description, internal_championship_id, played_at, logo, map, rule_file, rule_text, player_by_team, team_by_flight, for_championship, published_at FROM competition');
        $this->addSql('DROP TABLE competition');
        $this->addSql('CREATE TABLE competition (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, championship_id INTEGER NOT NULL, name VARCHAR(255) NOT NULL COLLATE BINARY, description CLOB DEFAULT NULL COLLATE BINARY, internal_championship_id INTEGER NOT NULL, played_at DATETIME NOT NULL, logo VARCHAR(255) DEFAULT NULL COLLATE BINARY, map VARCHAR(255) DEFAULT NULL COLLATE BINARY, rule_file VARCHAR(255) DEFAULT NULL COLLATE BINARY, rule_text CLOB DEFAULT NULL COLLATE BINARY, player_by_team INTEGER NOT NULL, team_by_flight INTEGER NOT NULL, for_championship BOOLEAN NOT NULL, published_at DATETIME NOT NULL, CONSTRAINT FK_B50A2CB194DDBCE9 FOREIGN KEY (championship_id) REFERENCES championship (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO competition (id, championship_id, name, description, internal_championship_id, played_at, logo, map, rule_file, rule_text, player_by_team, team_by_flight, for_championship, published_at) SELECT id, championship_id, name, description, internal_championship_id, played_at, logo, map, rule_file, rule_text, player_by_team, team_by_flight, for_championship, published_at FROM __temp__competition');
        $this->addSql('DROP TABLE __temp__competition');
        $this->addSql('CREATE INDEX IDX_B50A2CB194DDBCE9 ON competition (championship_id)');
        $this->addSql('DROP INDEX IDX_668EA3837B39D312');
        $this->addSql('DROP INDEX IDX_668EA38315ADE12C');
        $this->addSql('CREATE TEMPORARY TABLE __temp__competition_hole AS SELECT competition_id, hole_id FROM competition_hole');
        $this->addSql('DROP TABLE competition_hole');
        $this->addSql('CREATE TABLE competition_hole (competition_id INTEGER NOT NULL, hole_id INTEGER NOT NULL, PRIMARY KEY(competition_id, hole_id), CONSTRAINT FK_668EA3837B39D312 FOREIGN KEY (competition_id) REFERENCES competition (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_668EA38315ADE12C FOREIGN KEY (hole_id) REFERENCES hole (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO competition_hole (competition_id, hole_id) SELECT competition_id, hole_id FROM __temp__competition_hole');
        $this->addSql('DROP TABLE __temp__competition_hole');
        $this->addSql('CREATE INDEX IDX_668EA3837B39D312 ON competition_hole (competition_id)');
        $this->addSql('CREATE INDEX IDX_668EA38315ADE12C ON competition_hole (hole_id)');
        $this->addSql('DROP INDEX IDX_83D0485B7B39D312');
        $this->addSql('DROP INDEX IDX_83D0485BA76ED395');
        $this->addSql('CREATE TEMPORARY TABLE __temp__competition_user AS SELECT competition_id, user_id FROM competition_user');
        $this->addSql('DROP TABLE competition_user');
        $this->addSql('CREATE TABLE competition_user (competition_id INTEGER NOT NULL, user_id INTEGER NOT NULL, PRIMARY KEY(competition_id, user_id), CONSTRAINT FK_83D0485B7B39D312 FOREIGN KEY (competition_id) REFERENCES competition (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_83D0485BA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO competition_user (competition_id, user_id) SELECT competition_id, user_id FROM __temp__competition_user');
        $this->addSql('DROP TABLE __temp__competition_user');
        $this->addSql('CREATE INDEX IDX_83D0485B7B39D312 ON competition_user (competition_id)');
        $this->addSql('CREATE INDEX IDX_83D0485BA76ED395 ON competition_user (user_id)');
        $this->addSql('DROP INDEX IDX_3E2B3EAD7B39D312');
        $this->addSql('DROP INDEX IDX_3E2B3EAD99E6F5DF');
        $this->addSql('CREATE TEMPORARY TABLE __temp__competition_rank_player AS SELECT id, competition_id, player_id, rank, total_hit, delta_hit, score FROM competition_rank_player');
        $this->addSql('DROP TABLE competition_rank_player');
        $this->addSql('CREATE TABLE competition_rank_player (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, competition_id INTEGER NOT NULL, player_id INTEGER NOT NULL, rank INTEGER NOT NULL, total_hit INTEGER NOT NULL, delta_hit INTEGER NOT NULL, score INTEGER NOT NULL, CONSTRAINT FK_3E2B3EAD7B39D312 FOREIGN KEY (competition_id) REFERENCES competition (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_3E2B3EAD99E6F5DF FOREIGN KEY (player_id) REFERENCES player (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO competition_rank_player (id, competition_id, player_id, rank, total_hit, delta_hit, score) SELECT id, competition_id, player_id, rank, total_hit, delta_hit, score FROM __temp__competition_rank_player');
        $this->addSql('DROP TABLE __temp__competition_rank_player');
        $this->addSql('CREATE INDEX IDX_3E2B3EAD7B39D312 ON competition_rank_player (competition_id)');
        $this->addSql('CREATE INDEX IDX_3E2B3EAD99E6F5DF ON competition_rank_player (player_id)');
        $this->addSql('DROP INDEX IDX_69A0FA827B39D312');
        $this->addSql('DROP INDEX IDX_69A0FA82296CD8AE');
        $this->addSql('CREATE TEMPORARY TABLE __temp__competition_rank_team AS SELECT id, competition_id, team_id, rank, total_hit, delta_hit, score FROM competition_rank_team');
        $this->addSql('DROP TABLE competition_rank_team');
        $this->addSql('CREATE TABLE competition_rank_team (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, competition_id INTEGER NOT NULL, team_id INTEGER NOT NULL, rank INTEGER NOT NULL, total_hit INTEGER NOT NULL, delta_hit INTEGER NOT NULL, score INTEGER NOT NULL, CONSTRAINT FK_69A0FA827B39D312 FOREIGN KEY (competition_id) REFERENCES competition (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_69A0FA82296CD8AE FOREIGN KEY (team_id) REFERENCES team (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO competition_rank_team (id, competition_id, team_id, rank, total_hit, delta_hit, score) SELECT id, competition_id, team_id, rank, total_hit, delta_hit, score FROM __temp__competition_rank_team');
        $this->addSql('DROP TABLE __temp__competition_rank_team');
        $this->addSql('CREATE INDEX IDX_69A0FA827B39D312 ON competition_rank_team (competition_id)');
        $this->addSql('CREATE INDEX IDX_69A0FA82296CD8AE ON competition_rank_team (team_id)');
        $this->addSql('DROP INDEX IDX_C257E60E7B39D312');
        $this->addSql('CREATE TEMPORARY TABLE __temp__flight AS SELECT id, competition_id, internal_competition_id FROM flight');
        $this->addSql('DROP TABLE flight');
        $this->addSql('CREATE TABLE flight (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, competition_id INTEGER NOT NULL, internal_competition_id INTEGER NOT NULL, CONSTRAINT FK_C257E60E7B39D312 FOREIGN KEY (competition_id) REFERENCES competition (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO flight (id, competition_id, internal_competition_id) SELECT id, competition_id, internal_competition_id FROM __temp__flight');
        $this->addSql('DROP TABLE __temp__flight');
        $this->addSql('CREATE INDEX IDX_C257E60E7B39D312 ON flight (competition_id)');
        $this->addSql('DROP INDEX IDX_CAD8B2E91F478C5');
        $this->addSql('DROP INDEX IDX_CAD8B2EA76ED395');
        $this->addSql('CREATE TEMPORARY TABLE __temp__flight_user AS SELECT flight_id, user_id FROM flight_user');
        $this->addSql('DROP TABLE flight_user');
        $this->addSql('CREATE TABLE flight_user (flight_id INTEGER NOT NULL, user_id INTEGER NOT NULL, PRIMARY KEY(flight_id, user_id), CONSTRAINT FK_CAD8B2E91F478C5 FOREIGN KEY (flight_id) REFERENCES flight (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_CAD8B2EA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO flight_user (flight_id, user_id) SELECT flight_id, user_id FROM __temp__flight_user');
        $this->addSql('DROP TABLE __temp__flight_user');
        $this->addSql('CREATE INDEX IDX_CAD8B2E91F478C5 ON flight_user (flight_id)');
        $this->addSql('CREATE INDEX IDX_CAD8B2EA76ED395 ON flight_user (user_id)');
        $this->addSql('DROP INDEX IDX_68CD3D91744E0351');
        $this->addSql('DROP INDEX IDX_68CD3D91DD842E46');
        $this->addSql('DROP INDEX IDX_68CD3D91DFE3779D');
        $this->addSql('CREATE TEMPORARY TABLE __temp__hole AS SELECT id, rule_id, position_id, referees_id, name, description, par FROM hole');
        $this->addSql('DROP TABLE hole');
        $this->addSql('CREATE TABLE hole (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, rule_id INTEGER NOT NULL, position_id INTEGER DEFAULT NULL, referees_id INTEGER DEFAULT NULL, name VARCHAR(255) NOT NULL COLLATE BINARY, description CLOB DEFAULT NULL COLLATE BINARY, par INTEGER NOT NULL, CONSTRAINT FK_68CD3D91744E0351 FOREIGN KEY (rule_id) REFERENCES rule (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_68CD3D91DD842E46 FOREIGN KEY (position_id) REFERENCES position (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_68CD3D91DFE3779D FOREIGN KEY (referees_id) REFERENCES user (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO hole (id, rule_id, position_id, referees_id, name, description, par) SELECT id, rule_id, position_id, referees_id, name, description, par FROM __temp__hole');
        $this->addSql('DROP TABLE __temp__hole');
        $this->addSql('CREATE INDEX IDX_68CD3D91744E0351 ON hole (rule_id)');
        $this->addSql('CREATE INDEX IDX_68CD3D91DD842E46 ON hole (position_id)');
        $this->addSql('CREATE INDEX IDX_68CD3D91DFE3779D ON hole (referees_id)');
        $this->addSql('DROP INDEX IDX_98197A65296CD8AE');
        $this->addSql('CREATE TEMPORARY TABLE __temp__player AS SELECT id, team_id, firstname, lastname, nickname, picture, is4_championship FROM player');
        $this->addSql('DROP TABLE player');
        $this->addSql('CREATE TABLE player (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, team_id INTEGER DEFAULT NULL, firstname VARCHAR(255) NOT NULL COLLATE BINARY, lastname VARCHAR(255) NOT NULL COLLATE BINARY, nickname VARCHAR(255) DEFAULT NULL COLLATE BINARY, picture VARCHAR(255) DEFAULT NULL COLLATE BINARY, is4_championship BOOLEAN NOT NULL, CONSTRAINT FK_98197A65296CD8AE FOREIGN KEY (team_id) REFERENCES team (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO player (id, team_id, firstname, lastname, nickname, picture, is4_championship) SELECT id, team_id, firstname, lastname, nickname, picture, is4_championship FROM __temp__player');
        $this->addSql('DROP TABLE __temp__player');
        $this->addSql('CREATE INDEX IDX_98197A65296CD8AE ON player (team_id)');
        $this->addSql('DROP INDEX IDX_7DF3E98894DDBCE9');
        $this->addSql('CREATE TEMPORARY TABLE __temp__player_ranking_calculus AS SELECT id, championship_id, rank, score FROM player_ranking_calculus');
        $this->addSql('DROP TABLE player_ranking_calculus');
        $this->addSql('CREATE TABLE player_ranking_calculus (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, championship_id INTEGER NOT NULL, rank INTEGER NOT NULL, score INTEGER NOT NULL, CONSTRAINT FK_7DF3E98894DDBCE9 FOREIGN KEY (championship_id) REFERENCES championship (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO player_ranking_calculus (id, championship_id, rank, score) SELECT id, championship_id, rank, score FROM __temp__player_ranking_calculus');
        $this->addSql('DROP TABLE __temp__player_ranking_calculus');
        $this->addSql('CREATE INDEX IDX_7DF3E98894DDBCE9 ON player_ranking_calculus (championship_id)');
        $this->addSql('DROP INDEX IDX_136AC11399E6F5DF');
        $this->addSql('DROP INDEX IDX_136AC11315ADE12C');
        $this->addSql('DROP INDEX IDX_136AC1137B39D312');
        $this->addSql('CREATE TEMPORARY TABLE __temp__result AS SELECT id, player_id, hole_id, competition_id, score FROM result');
        $this->addSql('DROP TABLE result');
        $this->addSql('CREATE TABLE result (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, player_id INTEGER NOT NULL, hole_id INTEGER NOT NULL, competition_id INTEGER NOT NULL, score INTEGER NOT NULL, CONSTRAINT FK_136AC11399E6F5DF FOREIGN KEY (player_id) REFERENCES player (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_136AC11315ADE12C FOREIGN KEY (hole_id) REFERENCES hole (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_136AC1137B39D312 FOREIGN KEY (competition_id) REFERENCES competition (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO result (id, player_id, hole_id, competition_id, score) SELECT id, player_id, hole_id, competition_id, score FROM __temp__result');
        $this->addSql('DROP TABLE __temp__result');
        $this->addSql('CREATE INDEX IDX_136AC11399E6F5DF ON result (player_id)');
        $this->addSql('CREATE INDEX IDX_136AC11315ADE12C ON result (hole_id)');
        $this->addSql('CREATE INDEX IDX_136AC1137B39D312 ON result (competition_id)');
        $this->addSql('DROP INDEX IDX_C4E0A61F61190A32');
        $this->addSql('DROP INDEX IDX_C4E0A61F7B39D312');
        $this->addSql('DROP INDEX IDX_C4E0A61F91F478C5');
        $this->addSql('CREATE TEMPORARY TABLE __temp__team AS SELECT id, club_id, competition_id, flight_id, name, is4_championship FROM team');
        $this->addSql('DROP TABLE team');
        $this->addSql('CREATE TABLE team (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, club_id INTEGER DEFAULT NULL, competition_id INTEGER DEFAULT NULL, flight_id INTEGER DEFAULT NULL, name VARCHAR(255) NOT NULL COLLATE BINARY, is4_championship BOOLEAN NOT NULL, CONSTRAINT FK_C4E0A61F61190A32 FOREIGN KEY (club_id) REFERENCES club (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_C4E0A61F7B39D312 FOREIGN KEY (competition_id) REFERENCES competition (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_C4E0A61F91F478C5 FOREIGN KEY (flight_id) REFERENCES flight (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO team (id, club_id, competition_id, flight_id, name, is4_championship) SELECT id, club_id, competition_id, flight_id, name, is4_championship FROM __temp__team');
        $this->addSql('DROP TABLE __temp__team');
        $this->addSql('CREATE INDEX IDX_C4E0A61F61190A32 ON team (club_id)');
        $this->addSql('CREATE INDEX IDX_C4E0A61F7B39D312 ON team (competition_id)');
        $this->addSql('CREATE INDEX IDX_C4E0A61F91F478C5 ON team (flight_id)');
        $this->addSql('DROP INDEX IDX_2BBA693294DDBCE9');
        $this->addSql('CREATE TEMPORARY TABLE __temp__team_ranking_calculus AS SELECT id, championship_id, rank, score FROM team_ranking_calculus');
        $this->addSql('DROP TABLE team_ranking_calculus');
        $this->addSql('CREATE TABLE team_ranking_calculus (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, championship_id INTEGER NOT NULL, rank INTEGER NOT NULL, score INTEGER NOT NULL, CONSTRAINT FK_2BBA693294DDBCE9 FOREIGN KEY (championship_id) REFERENCES championship (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO team_ranking_calculus (id, championship_id, rank, score) SELECT id, championship_id, rank, score FROM __temp__team_ranking_calculus');
        $this->addSql('DROP TABLE __temp__team_ranking_calculus');
        $this->addSql('CREATE INDEX IDX_2BBA693294DDBCE9 ON team_ranking_calculus (championship_id)');
        $this->addSql('DROP INDEX UNIQ_8D93D649F85E0677');
        $this->addSql('DROP INDEX IDX_8D93D64961190A32');
        $this->addSql('CREATE TEMPORARY TABLE __temp__user AS SELECT id, club_id, username, roles, password, simplified_password FROM user');
        $this->addSql('DROP TABLE user');
        $this->addSql('CREATE TABLE user (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, club_id INTEGER DEFAULT NULL, username VARCHAR(180) NOT NULL COLLATE BINARY, roles CLOB NOT NULL COLLATE BINARY --(DC2Type:json)
        , password VARCHAR(255) NOT NULL COLLATE BINARY, simplified_password INTEGER DEFAULT NULL, CONSTRAINT FK_8D93D64961190A32 FOREIGN KEY (club_id) REFERENCES club (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO user (id, club_id, username, roles, password, simplified_password) SELECT id, club_id, username, roles, password, simplified_password FROM __temp__user');
        $this->addSql('DROP TABLE __temp__user');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649F85E0677 ON user (username)');
        $this->addSql('CREATE INDEX IDX_8D93D64961190A32 ON user (club_id)');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP INDEX IDX_EBADDE6A4EC001D1');
        $this->addSql('CREATE TEMPORARY TABLE __temp__championship AS SELECT id, season_id, name, description, logo, updated_at, number_competition_max4_calculus, is_internal FROM championship');
        $this->addSql('DROP TABLE championship');
        $this->addSql('CREATE TABLE championship (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, season_id INTEGER NOT NULL, name VARCHAR(255) NOT NULL, description CLOB DEFAULT NULL, logo VARCHAR(255) NOT NULL, updated_at DATETIME NOT NULL, number_competition_max4_calculus INTEGER NOT NULL, is_internal BOOLEAN NOT NULL)');
        $this->addSql('INSERT INTO championship (id, season_id, name, description, logo, updated_at, number_competition_max4_calculus, is_internal) SELECT id, season_id, name, description, logo, updated_at, number_competition_max4_calculus, is_internal FROM __temp__championship');
        $this->addSql('DROP TABLE __temp__championship');
        $this->addSql('CREATE INDEX IDX_EBADDE6A4EC001D1 ON championship (season_id)');
        $this->addSql('DROP INDEX IDX_D93D873294DDBCE9');
        $this->addSql('DROP INDEX IDX_D93D873261190A32');
        $this->addSql('CREATE TEMPORARY TABLE __temp__championship_rank_club AS SELECT id, championship_id, club_id, rank, score FROM championship_rank_club');
        $this->addSql('DROP TABLE championship_rank_club');
        $this->addSql('CREATE TABLE championship_rank_club (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, championship_id INTEGER NOT NULL, club_id INTEGER NOT NULL, rank INTEGER NOT NULL, score INTEGER NOT NULL)');
        $this->addSql('INSERT INTO championship_rank_club (id, championship_id, club_id, rank, score) SELECT id, championship_id, club_id, rank, score FROM __temp__championship_rank_club');
        $this->addSql('DROP TABLE __temp__championship_rank_club');
        $this->addSql('CREATE INDEX IDX_D93D873294DDBCE9 ON championship_rank_club (championship_id)');
        $this->addSql('CREATE INDEX IDX_D93D873261190A32 ON championship_rank_club (club_id)');
        $this->addSql('DROP INDEX IDX_33BEFAAE94DDBCE9');
        $this->addSql('DROP INDEX IDX_33BEFAAE99E6F5DF');
        $this->addSql('CREATE TEMPORARY TABLE __temp__championship_rank_player AS SELECT id, championship_id, player_id, rank, score FROM championship_rank_player');
        $this->addSql('DROP TABLE championship_rank_player');
        $this->addSql('CREATE TABLE championship_rank_player (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, championship_id INTEGER NOT NULL, player_id INTEGER NOT NULL, rank INTEGER NOT NULL, score INTEGER NOT NULL)');
        $this->addSql('INSERT INTO championship_rank_player (id, championship_id, player_id, rank, score) SELECT id, championship_id, player_id, rank, score FROM __temp__championship_rank_player');
        $this->addSql('DROP TABLE __temp__championship_rank_player');
        $this->addSql('CREATE INDEX IDX_33BEFAAE94DDBCE9 ON championship_rank_player (championship_id)');
        $this->addSql('CREATE INDEX IDX_33BEFAAE99E6F5DF ON championship_rank_player (player_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__club AS SELECT id, name, description, logo FROM club');
        $this->addSql('DROP TABLE club');
        $this->addSql('CREATE TABLE club (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description CLOB DEFAULT NULL, logo VARCHAR(255) DEFAULT NULL)');
        $this->addSql('INSERT INTO club (id, name, description, logo) SELECT id, name, description, logo FROM __temp__club');
        $this->addSql('DROP TABLE __temp__club');
        $this->addSql('DROP INDEX IDX_B50A2CB194DDBCE9');
        $this->addSql('CREATE TEMPORARY TABLE __temp__competition AS SELECT id, championship_id, name, description, internal_championship_id, played_at, logo, map, rule_file, rule_text, player_by_team, team_by_flight, for_championship, published_at FROM competition');
        $this->addSql('DROP TABLE competition');
        $this->addSql('CREATE TABLE competition (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, championship_id INTEGER NOT NULL, name VARCHAR(255) NOT NULL, description CLOB DEFAULT NULL, internal_championship_id INTEGER NOT NULL, played_at DATETIME NOT NULL, logo VARCHAR(255) DEFAULT NULL, map VARCHAR(255) DEFAULT NULL, rule_file VARCHAR(255) DEFAULT NULL, rule_text CLOB DEFAULT NULL, player_by_team INTEGER NOT NULL, team_by_flight INTEGER NOT NULL, for_championship BOOLEAN NOT NULL, published_at DATETIME NOT NULL)');
        $this->addSql('INSERT INTO competition (id, championship_id, name, description, internal_championship_id, played_at, logo, map, rule_file, rule_text, player_by_team, team_by_flight, for_championship, published_at) SELECT id, championship_id, name, description, internal_championship_id, played_at, logo, map, rule_file, rule_text, player_by_team, team_by_flight, for_championship, published_at FROM __temp__competition');
        $this->addSql('DROP TABLE __temp__competition');
        $this->addSql('CREATE INDEX IDX_B50A2CB194DDBCE9 ON competition (championship_id)');
        $this->addSql('DROP INDEX IDX_668EA3837B39D312');
        $this->addSql('DROP INDEX IDX_668EA38315ADE12C');
        $this->addSql('CREATE TEMPORARY TABLE __temp__competition_hole AS SELECT competition_id, hole_id FROM competition_hole');
        $this->addSql('DROP TABLE competition_hole');
        $this->addSql('CREATE TABLE competition_hole (competition_id INTEGER NOT NULL, hole_id INTEGER NOT NULL, PRIMARY KEY(competition_id, hole_id))');
        $this->addSql('INSERT INTO competition_hole (competition_id, hole_id) SELECT competition_id, hole_id FROM __temp__competition_hole');
        $this->addSql('DROP TABLE __temp__competition_hole');
        $this->addSql('CREATE INDEX IDX_668EA3837B39D312 ON competition_hole (competition_id)');
        $this->addSql('CREATE INDEX IDX_668EA38315ADE12C ON competition_hole (hole_id)');
        $this->addSql('DROP INDEX IDX_3E2B3EAD7B39D312');
        $this->addSql('DROP INDEX IDX_3E2B3EAD99E6F5DF');
        $this->addSql('CREATE TEMPORARY TABLE __temp__competition_rank_player AS SELECT id, competition_id, player_id, rank, total_hit, delta_hit, score FROM competition_rank_player');
        $this->addSql('DROP TABLE competition_rank_player');
        $this->addSql('CREATE TABLE competition_rank_player (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, competition_id INTEGER NOT NULL, player_id INTEGER NOT NULL, rank INTEGER NOT NULL, total_hit INTEGER NOT NULL, delta_hit INTEGER NOT NULL, score INTEGER NOT NULL)');
        $this->addSql('INSERT INTO competition_rank_player (id, competition_id, player_id, rank, total_hit, delta_hit, score) SELECT id, competition_id, player_id, rank, total_hit, delta_hit, score FROM __temp__competition_rank_player');
        $this->addSql('DROP TABLE __temp__competition_rank_player');
        $this->addSql('CREATE INDEX IDX_3E2B3EAD7B39D312 ON competition_rank_player (competition_id)');
        $this->addSql('CREATE INDEX IDX_3E2B3EAD99E6F5DF ON competition_rank_player (player_id)');
        $this->addSql('DROP INDEX IDX_69A0FA827B39D312');
        $this->addSql('DROP INDEX IDX_69A0FA82296CD8AE');
        $this->addSql('CREATE TEMPORARY TABLE __temp__competition_rank_team AS SELECT id, competition_id, team_id, rank, total_hit, delta_hit, score FROM competition_rank_team');
        $this->addSql('DROP TABLE competition_rank_team');
        $this->addSql('CREATE TABLE competition_rank_team (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, competition_id INTEGER NOT NULL, team_id INTEGER NOT NULL, rank INTEGER NOT NULL, total_hit INTEGER NOT NULL, delta_hit INTEGER NOT NULL, score INTEGER NOT NULL)');
        $this->addSql('INSERT INTO competition_rank_team (id, competition_id, team_id, rank, total_hit, delta_hit, score) SELECT id, competition_id, team_id, rank, total_hit, delta_hit, score FROM __temp__competition_rank_team');
        $this->addSql('DROP TABLE __temp__competition_rank_team');
        $this->addSql('CREATE INDEX IDX_69A0FA827B39D312 ON competition_rank_team (competition_id)');
        $this->addSql('CREATE INDEX IDX_69A0FA82296CD8AE ON competition_rank_team (team_id)');
        $this->addSql('DROP INDEX IDX_83D0485B7B39D312');
        $this->addSql('DROP INDEX IDX_83D0485BA76ED395');
        $this->addSql('CREATE TEMPORARY TABLE __temp__competition_user AS SELECT competition_id, user_id FROM competition_user');
        $this->addSql('DROP TABLE competition_user');
        $this->addSql('CREATE TABLE competition_user (competition_id INTEGER NOT NULL, user_id INTEGER NOT NULL, PRIMARY KEY(competition_id, user_id))');
        $this->addSql('INSERT INTO competition_user (competition_id, user_id) SELECT competition_id, user_id FROM __temp__competition_user');
        $this->addSql('DROP TABLE __temp__competition_user');
        $this->addSql('CREATE INDEX IDX_83D0485B7B39D312 ON competition_user (competition_id)');
        $this->addSql('CREATE INDEX IDX_83D0485BA76ED395 ON competition_user (user_id)');
        $this->addSql('DROP INDEX IDX_C257E60E7B39D312');
        $this->addSql('CREATE TEMPORARY TABLE __temp__flight AS SELECT id, competition_id, internal_competition_id FROM flight');
        $this->addSql('DROP TABLE flight');
        $this->addSql('CREATE TABLE flight (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, competition_id INTEGER NOT NULL, internal_competition_id INTEGER NOT NULL)');
        $this->addSql('INSERT INTO flight (id, competition_id, internal_competition_id) SELECT id, competition_id, internal_competition_id FROM __temp__flight');
        $this->addSql('DROP TABLE __temp__flight');
        $this->addSql('CREATE INDEX IDX_C257E60E7B39D312 ON flight (competition_id)');
        $this->addSql('DROP INDEX IDX_CAD8B2E91F478C5');
        $this->addSql('DROP INDEX IDX_CAD8B2EA76ED395');
        $this->addSql('CREATE TEMPORARY TABLE __temp__flight_user AS SELECT flight_id, user_id FROM flight_user');
        $this->addSql('DROP TABLE flight_user');
        $this->addSql('CREATE TABLE flight_user (flight_id INTEGER NOT NULL, user_id INTEGER NOT NULL, PRIMARY KEY(flight_id, user_id))');
        $this->addSql('INSERT INTO flight_user (flight_id, user_id) SELECT flight_id, user_id FROM __temp__flight_user');
        $this->addSql('DROP TABLE __temp__flight_user');
        $this->addSql('CREATE INDEX IDX_CAD8B2E91F478C5 ON flight_user (flight_id)');
        $this->addSql('CREATE INDEX IDX_CAD8B2EA76ED395 ON flight_user (user_id)');
        $this->addSql('DROP INDEX IDX_68CD3D91744E0351');
        $this->addSql('DROP INDEX IDX_68CD3D91DD842E46');
        $this->addSql('DROP INDEX IDX_68CD3D91DFE3779D');
        $this->addSql('CREATE TEMPORARY TABLE __temp__hole AS SELECT id, rule_id, position_id, referees_id, name, description, par FROM hole');
        $this->addSql('DROP TABLE hole');
        $this->addSql('CREATE TABLE hole (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, rule_id INTEGER NOT NULL, position_id INTEGER DEFAULT NULL, referees_id INTEGER DEFAULT NULL, name VARCHAR(255) NOT NULL, description CLOB DEFAULT NULL, par INTEGER NOT NULL)');
        $this->addSql('INSERT INTO hole (id, rule_id, position_id, referees_id, name, description, par) SELECT id, rule_id, position_id, referees_id, name, description, par FROM __temp__hole');
        $this->addSql('DROP TABLE __temp__hole');
        $this->addSql('CREATE INDEX IDX_68CD3D91744E0351 ON hole (rule_id)');
        $this->addSql('CREATE INDEX IDX_68CD3D91DD842E46 ON hole (position_id)');
        $this->addSql('CREATE INDEX IDX_68CD3D91DFE3779D ON hole (referees_id)');
        $this->addSql('DROP INDEX IDX_98197A65296CD8AE');
        $this->addSql('CREATE TEMPORARY TABLE __temp__player AS SELECT id, team_id, firstname, lastname, nickname, picture, is4_championship FROM player');
        $this->addSql('DROP TABLE player');
        $this->addSql('CREATE TABLE player (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, team_id INTEGER DEFAULT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, nickname VARCHAR(255) DEFAULT NULL, picture VARCHAR(255) DEFAULT NULL, is4_championship BOOLEAN NOT NULL)');
        $this->addSql('INSERT INTO player (id, team_id, firstname, lastname, nickname, picture, is4_championship) SELECT id, team_id, firstname, lastname, nickname, picture, is4_championship FROM __temp__player');
        $this->addSql('DROP TABLE __temp__player');
        $this->addSql('CREATE INDEX IDX_98197A65296CD8AE ON player (team_id)');
        $this->addSql('DROP INDEX IDX_7DF3E98894DDBCE9');
        $this->addSql('CREATE TEMPORARY TABLE __temp__player_ranking_calculus AS SELECT id, championship_id, rank, score FROM player_ranking_calculus');
        $this->addSql('DROP TABLE player_ranking_calculus');
        $this->addSql('CREATE TABLE player_ranking_calculus (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, championship_id INTEGER NOT NULL, rank INTEGER NOT NULL, score INTEGER NOT NULL)');
        $this->addSql('INSERT INTO player_ranking_calculus (id, championship_id, rank, score) SELECT id, championship_id, rank, score FROM __temp__player_ranking_calculus');
        $this->addSql('DROP TABLE __temp__player_ranking_calculus');
        $this->addSql('CREATE INDEX IDX_7DF3E98894DDBCE9 ON player_ranking_calculus (championship_id)');
        $this->addSql('DROP INDEX IDX_136AC11399E6F5DF');
        $this->addSql('DROP INDEX IDX_136AC11315ADE12C');
        $this->addSql('DROP INDEX IDX_136AC1137B39D312');
        $this->addSql('CREATE TEMPORARY TABLE __temp__result AS SELECT id, player_id, hole_id, competition_id, score FROM result');
        $this->addSql('DROP TABLE result');
        $this->addSql('CREATE TABLE result (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, player_id INTEGER NOT NULL, hole_id INTEGER NOT NULL, competition_id INTEGER NOT NULL, score INTEGER NOT NULL)');
        $this->addSql('INSERT INTO result (id, player_id, hole_id, competition_id, score) SELECT id, player_id, hole_id, competition_id, score FROM __temp__result');
        $this->addSql('DROP TABLE __temp__result');
        $this->addSql('CREATE INDEX IDX_136AC11399E6F5DF ON result (player_id)');
        $this->addSql('CREATE INDEX IDX_136AC11315ADE12C ON result (hole_id)');
        $this->addSql('CREATE INDEX IDX_136AC1137B39D312 ON result (competition_id)');
        $this->addSql('DROP INDEX IDX_C4E0A61F61190A32');
        $this->addSql('DROP INDEX IDX_C4E0A61F7B39D312');
        $this->addSql('DROP INDEX IDX_C4E0A61F91F478C5');
        $this->addSql('CREATE TEMPORARY TABLE __temp__team AS SELECT id, club_id, competition_id, flight_id, name, is4_championship FROM team');
        $this->addSql('DROP TABLE team');
        $this->addSql('CREATE TABLE team (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, club_id INTEGER DEFAULT NULL, competition_id INTEGER DEFAULT NULL, flight_id INTEGER DEFAULT NULL, name VARCHAR(255) NOT NULL, is4_championship BOOLEAN NOT NULL)');
        $this->addSql('INSERT INTO team (id, club_id, competition_id, flight_id, name, is4_championship) SELECT id, club_id, competition_id, flight_id, name, is4_championship FROM __temp__team');
        $this->addSql('DROP TABLE __temp__team');
        $this->addSql('CREATE INDEX IDX_C4E0A61F61190A32 ON team (club_id)');
        $this->addSql('CREATE INDEX IDX_C4E0A61F7B39D312 ON team (competition_id)');
        $this->addSql('CREATE INDEX IDX_C4E0A61F91F478C5 ON team (flight_id)');
        $this->addSql('DROP INDEX IDX_2BBA693294DDBCE9');
        $this->addSql('CREATE TEMPORARY TABLE __temp__team_ranking_calculus AS SELECT id, championship_id, rank, score FROM team_ranking_calculus');
        $this->addSql('DROP TABLE team_ranking_calculus');
        $this->addSql('CREATE TABLE team_ranking_calculus (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, championship_id INTEGER NOT NULL, rank INTEGER NOT NULL, score INTEGER NOT NULL)');
        $this->addSql('INSERT INTO team_ranking_calculus (id, championship_id, rank, score) SELECT id, championship_id, rank, score FROM __temp__team_ranking_calculus');
        $this->addSql('DROP TABLE __temp__team_ranking_calculus');
        $this->addSql('CREATE INDEX IDX_2BBA693294DDBCE9 ON team_ranking_calculus (championship_id)');
        $this->addSql('DROP INDEX UNIQ_8D93D649F85E0677');
        $this->addSql('DROP INDEX IDX_8D93D64961190A32');
        $this->addSql('CREATE TEMPORARY TABLE __temp__user AS SELECT id, club_id, username, roles, password, simplified_password FROM user');
        $this->addSql('DROP TABLE user');
        $this->addSql('CREATE TABLE user (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, club_id INTEGER DEFAULT NULL, username VARCHAR(180) NOT NULL, roles CLOB NOT NULL --(DC2Type:json)
        , password VARCHAR(255) NOT NULL, simplified_password INTEGER DEFAULT NULL)');
        $this->addSql('INSERT INTO user (id, club_id, username, roles, password, simplified_password) SELECT id, club_id, username, roles, password, simplified_password FROM __temp__user');
        $this->addSql('DROP TABLE __temp__user');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649F85E0677 ON user (username)');
        $this->addSql('CREATE INDEX IDX_8D93D64961190A32 ON user (club_id)');
    }
}
